import numpy as np
import pandas as pd

def write_xyz(path, elems, coords):
    with open(path, 'w') as f:
        f.write(f"{len(elems)}\nGenerated by script\n")
        for e, (x, y, z) in zip(elems, coords):
            f.write(f"{e:<3} {x:.6f} {y:.6f} {z:.6f}\n")

def read_xyz(path):
    with open(path, 'r') as f:
        lines = f.read().strip().splitlines()
    nat = int(lines[0])
    elems, coords = [], []
    for line in lines[2:2+nat]:
        parts = line.split()
        elems.append(parts[0])
        coords.append([float(parts[1]), float(parts[2]), float(parts[3])])
    return elems, np.array(coords)

def save_failed(failed, path):
    if failed:
        pd.DataFrame(failed).to_csv(path, index=False)

